name: Deploy sql-versioning-service (dev)

on:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  IMAGE_NAME: sql-versioning-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login (RBAC)
        run: |
          az acr login --name sqlversioningacrdev

      - name: Build + push image
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}"

          docker build -t "$IMAGE" .
          docker push "$IMAGE"

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update Container App image
        run: |
          az containerapp update \
            -g ${{ secrets.RESOURCE_GROUP }} \
            -n ${{ secrets.CONTAINER_APP_NAME }} \
            --image "$IMAGE"
